'use strict';window.tsfGBC=function($){const editor=wp.data.select('core/editor');const editPost=wp.data.select('core/edit-post');const{debounce}=lodash;let postData;function getPostAttribute(attribute){return editor.getEditedPostAttribute(attribute);}
function setData(){postData={title:getPostAttribute('title'),link:editor.getPermalink(),content:getPostAttribute('content'),excerpt:getPostAttribute('excerpt'),visibility:editor.getEditedPostVisibility(),};}
function getData(type){return postData[type]||null;}
function assessData(){let oldData=postData;setData();if(oldData.title!==postData.title){triggerUpdate('title');}
if(oldData.link!==postData.link){triggerUpdate('link');}
if(oldData.content!==postData.content){triggerUpdate('content');}
if(oldData.excerpt!==postData.excerpt){triggerUpdate('excerpt');}
if(oldData.visibility!==postData.visibility){triggerUpdate('visibility');}}
const triggerUpdate=type=>{$(document).trigger(`tsf-updated-gutenberg-${type}`,[getData(type)]);}
let saved=false;let savedType='';function saveDispatcher(){if(!saved){if(editor.isSavingPost()){if(editor.isPreviewingPost()){saved=true;savedType='preview';}else if(editor.isAutosavingPost()){saved=true;savedType='autosave';}else{saved=true;savedType='save';}}}else{if(editor.didPostSaveRequestSucceed()){dispatchSaveEventDebouncer();revertSaveStateDebouncer()&&revertSaveStateDebouncer().cancel();revertSaveState();}else{revertSaveStateDebouncer();}}}
const revertSaveStateDebouncer=debounce(revertSaveState,7000);function revertSaveState(){saved=false;}
const dispatchSaveEventDebouncer=debounce(dispatchSavedEvent,500);let retryDispatch=0;function dispatchSavedEvent(){if(editor.isPostSavingLocked()){if(++retryDispatch<3){dispatchSaveEventDebouncer();}else{dispatchSaveEventDebouncer()&&dispatchSaveEventDebouncer().cancel();retryDispatch=0;}}else{retryDispatch=0;let triggerOnSaveEvent=!editor.hasChangedContent();switch(savedType){case 'preview':document.dispatchEvent(new CustomEvent('tsf-gutenberg-onpreview'));break;case 'autosave':document.dispatchEvent(new CustomEvent('tsf-gutenberg-onautosave'));break;case 'save':triggerOnSaveEvent=true;break;}
if(triggerOnSaveEvent){document.dispatchEvent(new CustomEvent('tsf-gutenberg-onsave'))&&document.dispatchEvent(new CustomEvent('tsf-gutenberg-onsave-completed'));}
document.dispatchEvent(new CustomEvent('tsf-gutenberg-saved-document',{detail:{savedType}}));savedType='';}}
let lastSidebarState={opened:false,};function sidebarDispatcher(){if(editPost.isEditorSidebarOpened()){if(!lastSidebarState.opened){lastSidebarState.opened=true;document.dispatchEvent(new CustomEvent('tsf-gutenberg-sidebar-opened'));}}else{if(lastSidebarState.opened){lastSidebarState.opened=false;document.dispatchEvent(new CustomEvent('tsf-gutenberg-sidebar-closed'));}}}
const _initCompat=()=>{const{subscribe}=wp.data;subscribe(debounce(sidebarDispatcher,500));subscribe(debounce(assessData,300));subscribe(saveDispatcher);setTimeout(()=>{setData();triggerUpdate('title');triggerUpdate('link');triggerUpdate('content');triggerUpdate('excerpt');triggerUpdate('visibility');document.dispatchEvent(new CustomEvent('tsf-subscribed-to-gutenberg'));});}
return Object.assign({load:()=>{document.body.addEventListener('tsf-onload',_initCompat);},},{triggerUpdate,});}(jQuery);window.tsfGBC.load();