'use strict';window.tsfLe=function(){let dispatchTimeout;const _dispatchUpdate=()=>{clearTimeout(dispatchTimeout);dispatchTimeout=setTimeout(()=>{document.dispatchEvent(new Event('tsfLeUpdated'));},50);}
const _updated=()=>{tsfTT?.triggerReset();}
const _setInlinePostValues=id=>{const data=JSON.parse(document.getElementById(`tsfLeData[${id}]`)?.dataset.le||0)||{};for(const option in data){const element=document.getElementById('autodescription-quick[%s]'.replace('%s',option));if(!element)continue;if(data[option].isSelect){tsf.selectByValue(element,data[option].value);let _default=element.querySelector('[value="0"]');if(_default)
_default.innerHTML=_default.innerHTML.replace('%s',tsf.decodeEntities(data[option].default));}else{element.value=tsf.decodeEntities(data[option].value);if(data[option].placeholder)
element.placeholder=tsf.decodeEntities(data[option].placeholder);}}}
const _setInlineTermValues=id=>_setInlinePostValues(id);const _getPostData=id=>JSON.parse(document.getElementById(`tsfLePostData[${id}]`)?.dataset.lePostData||0)||{};const _setTitleVisibilityPrefix=event=>{let target=(event.originalEvent||event).target,titleId=target.dataset.tsfTitleId,prefixValue='',visibility='public';if('keep_private'===target.name){visibility=target.checked?'private':'public';}else{visibility=target.value&&target.value.length?'password':'public';}
switch(visibility){case 'password':prefixValue=tsfTitle.protectedPrefix;break;case 'private':prefixValue=tsfTitle.privatePrefix;break;default:case 'public':prefixValue='';break;}
tsfTitle.updateStateOf(titleId,'prefixValue',prefixValue);}
const _setDefaultTitle=event=>{const target=(event.originalEvent||event).target,titleId=target.dataset?.tsfTitleId,inputTitle=target.value?.trim()||'',termPrefix=target.dataset?.termPrefix?.trim()||'';let defaultTitle=tsfTitle.stripTitleTags?tsf.stripTags(inputTitle):inputTitle;defaultTitle||=tsfTitle.untitledTitle;if(termPrefix.length){if(window.isRtl){defaultTitle=`${defaultTitle} ${termPrefix}`;}else{defaultTitle=`${termPrefix} ${defaultTitle}`;}}
defaultTitle=tsf.escapeString(tsf.decodeEntities(defaultTitle.trim()));tsfTitle.updateStateOf(titleId,'defaultTitle',defaultTitle);}
const _prepareTitleInput=id=>{const titleId='autodescription-quick[doctitle]',titleInput=document.getElementById(titleId);tsfTitle.setInputElement(titleInput);const data=JSON.parse(document.getElementById(`tsfLeTitleData[${id}]`)?.dataset.leTitle||0);if(data){tsfTitle.updateStateOf(titleId,'allowReferenceChange',!data.refTitleLocked);tsfTitle.updateStateOf(titleId,'defaultTitle',data.defaultTitle.trim());tsfTitle.updateStateOf(titleId,'addAdditions',data.addAdditions);tsfTitle.updateStateOf(titleId,'additionValue',data.additionValue.trim());tsfTitle.updateStateOf(titleId,'additionPlacement',data.additionPlacement);}
let inlineEdit=document.getElementById(`edit-${id}`);if(inlineEdit){inlineEdit.querySelectorAll('[name=post_password]').forEach(element=>{element.dataset.tsfTitleId=titleId;element.addEventListener('input',_setTitleVisibilityPrefix);element.dispatchEvent(new CustomEvent('input'));});inlineEdit.querySelectorAll('[name=keep_private]').forEach(element=>{element.dataset.tsfTitleId=titleId;element.addEventListener('click',_setTitleVisibilityPrefix);element.dispatchEvent(new CustomEvent('click'));});inlineEdit.querySelectorAll('[name=post_title]').forEach(element=>{element.dataset.tsfTitleId=titleId;if(!_getPostData(id).isFront){element.addEventListener('input',_setDefaultTitle);element.dispatchEvent(new CustomEvent('input'));}});inlineEdit.querySelectorAll('[name=name]').forEach(element=>{element.dataset.tsfTitleId=titleId;element.dataset.termPrefix=data.termPrefix||'';element.addEventListener('input',_setDefaultTitle);element.dispatchEvent(new CustomEvent('input'));});}
tsfTT?.triggerReset();}
const _prepareDescriptionInput=id=>{const descId='autodescription-quick[description]',descInput=document.getElementById(descId);tsfDescription.setInputElement(descInput);const data=JSON.parse(document.getElementById(`tsfLeDescriptionData[${id}]`)?.dataset.leDescription||0);if(data){tsfDescription.updateStateOf(descId,'allowReferenceChange',!data.refDescriptionLocked);tsfDescription.updateStateOf(descId,'defaultDescription',data.defaultDescription.trim());}
tsfTT.triggerReset();}
const _setListeners=()=>{document.addEventListener('tsfLeDispatchUpdate',_dispatchUpdate);document.addEventListener('tsfLeUpdated',_updated);}
const _hijackListeners=()=>{let _oldInlineEditPost,_oldInlineEditTax;_oldInlineEditPost=window.inlineEditPost?.edit;if(_oldInlineEditPost){window.inlineEditPost.edit=function(id){let ret=_oldInlineEditPost.apply(this,arguments);if('object'===typeof id)
id=window.inlineEditPost?.getId(id);if(!id)return ret;_setInlinePostValues(id);_prepareTitleInput(id);_prepareDescriptionInput(id);window.tsfC?.resetCounterListener();return ret;}}
_oldInlineEditTax=window.inlineEditTax?.edit;if(_oldInlineEditTax){window.inlineEditTax.edit=function(id){let ret=_oldInlineEditTax.apply(this,arguments);if('object'===typeof id)
id=window.inlineEditTax?.getId(id);if(!id)return ret;_setInlineTermValues(id);_prepareTitleInput(id);_prepareDescriptionInput(id);window.tsfC?.resetCounterListener();return ret;}}}
return{load:()=>{document.body.addEventListener('tsf-onload',_setListeners);document.body.addEventListener('tsf-onload',_hijackListeners);}};}();window.tsfLe.load();