'use strict';window.tsfPost=function($){const l10n='undefined'!==typeof tsfPostL10n&&tsfPostL10n;const _titleId='autodescription_title';const _descId='autodescription_description';const _socialGroup='autodescription_social_singular';const _doFlexResizeListener=()=>{if(!document.querySelector('.tsf-flex'))return;let overflowAnimationFrame={};const calculateTextOverflow=target=>{let innerWrap=target.querySelector('.tsf-flex-nav-tab-inner'),navNames=target.getElementsByClassName('tsf-flex-nav-name');let displayNames=innerWrap.clientWidth<=target.clientWidth;if(displayNames){if(+(target.dataset.displayedNames||1))return;target.dataset.displayedNames=1;$(navNames).stop(false,true).fadeIn(250);}else{if(!+(target.dataset.displayedNames||1))return;target.dataset.displayedNames=0;$(navNames).hide();}
if(+target.dataset.displayedNames){if(innerWrap.clientWidth>target.clientWidth){$(navNames).stop(false,true).hide();target.dataset.displayedNames=0;}else{setTimeout(()=>{cancelAnimationFrame(overflowAnimationFrame[target.id]);overflowAnimationFrame[target.id]=requestAnimationFrame(()=>calculateTextOverflow(target));},7);}}}
const prepareCalculateTextOverflow=event=>{const target=event.detail.target||document.getElementById('tsf-flex-inpost-tabs-wrapper');if(target)
overflowAnimationFrame[target.id]=requestAnimationFrame(()=>calculateTextOverflow(target));}
window.addEventListener('tsf-flex-resize',prepareCalculateTextOverflow);const triggerResize=target=>{window.dispatchEvent(new CustomEvent('tsf-flex-resize',{bubbles:false,cancelable:false,detail:{target},}));}
let resizeAnimationFrame={};const resizeObserver=new ResizeObserver(entries=>{for(const entry of entries){let target=entry.target;cancelAnimationFrame(resizeAnimationFrame[target.id]);resizeAnimationFrame[target.id]=requestAnimationFrame(()=>{target.dataset.lastWidth||=0;if(+target.clientWidth!==+target.dataset.lastWidth){target.dataset.lastWidth=target.clientWidth;triggerResize(target);}});}});resizeObserver.observe(document.getElementById('tsf-flex-inpost-tabs-wrapper'));triggerResize();}
const _initTabs=()=>{tsfTabs.initStack('tsfSettings',{tabToggledEvent:new CustomEvent('tsf-flex-tab-toggled'),HTMLClasses:{wrapper:'tsf-flex-nav-tab-wrapper',tabRadio:'tsf-flex-nav-tab-radio',tabLabel:'tsf-flex-nav-tab-label',activeTab:'tsf-flex-tab-active',activeTabContent:'tsf-flex-tab-content-active',},fixHistory:true,});}
const _initVisibilityListeners=()=>{const indexSelect=document.getElementById('autodescription_noindex');if(!indexSelect)return;const canonicalInput=document.getElementById('autodescription_canonical');const BPROTECTED=0b01,BNOINDEX=0b10;let canonicalPhState=0b00,canonicalUrl='';let updateCanonicalPlaceholderDebouncer=void 0;const updateCanonicalPlaceholder=()=>{clearTimeout(updateCanonicalPlaceholderDebouncer);updateCanonicalPlaceholderDebouncer=setTimeout(()=>{if(!canonicalInput)return;canonicalUrl||=canonicalInput.placeholder;if((canonicalPhState&BPROTECTED)||(canonicalPhState&BNOINDEX)){canonicalInput.placeholder='';}else{canonicalInput.placeholder=canonicalUrl;}},50);}
const updateCanonical=link=>{canonicalUrl=link;updateCanonicalPlaceholder();}
$(document).on('tsf-updated-gutenberg-link',(event,link)=>updateCanonical(link));const setRobotsDefaultIndexingState=visibility=>{let _defaultIndexOption=indexSelect.querySelector('[value="0"]'),indexDefaultValue='';switch(visibility){case 'password':case 'private':indexDefaultValue='noindex';canonicalPhState|=BPROTECTED;break;default:case 'public':indexDefaultValue=indexSelect.dataset.defaultUnprotected;canonicalPhState&=~BPROTECTED;break;}
if(_defaultIndexOption)
_defaultIndexOption.innerHTML=indexSelect.dataset.defaultI18n.replace('%s',tsf.decodeEntities(indexDefaultValue));updateCanonicalPlaceholder();}
$(document).on('tsf-updated-gutenberg-visibility',(event,visibility)=>setRobotsDefaultIndexingState(visibility));const setClassicRobotsDefaultIndexingState=event=>{let visibility=$('#visibility').find('input:radio:checked').val();if('password'===visibility){let pass=$('#visibility').find('#post_password').val();if(!pass||!pass.length){visibility='public';}}
setRobotsDefaultIndexingState(visibility);}
document.querySelector('#visibility .save-post-visibility')?.addEventListener('click',setClassicRobotsDefaultIndexingState);if(l10n.states.isPrivate){setRobotsDefaultIndexingState('private');}else if(l10n.states.isProtected){setRobotsDefaultIndexingState('password');}else{setRobotsDefaultIndexingState('public');}
const setRobotsIndexingState=value=>{let type='';switch(+value){case 0:type=indexSelect.dataset.defaultUnprotected;break;case-1:type='index';break;case 1:type='noindex';break;}
if('noindex'===type){canonicalPhState|=BNOINDEX;}else{canonicalPhState&=~BNOINDEX;}
updateCanonicalPlaceholder();}
indexSelect.addEventListener('change',event=>setRobotsIndexingState(event.target.value));setRobotsIndexingState(indexSelect.value);}
const _initTitleListeners=()=>{const titleInput=document.getElementById(_titleId);if(!titleInput)return;tsfTitle.setInputElement(titleInput);const state=JSON.parse(document.getElementById(`tsf-title-data_${_titleId}`)?.dataset.state||0);if(state){tsfTitle.updateStateOf(_titleId,'allowReferenceChange',!state.refTitleLocked);tsfTitle.updateStateOf(_titleId,'defaultTitle',state.defaultTitle);tsfTitle.updateStateOf(_titleId,'addAdditions',state.addAdditions);tsfTitle.updateStateOf(_titleId,'additionValue',state.additionValue);tsfTitle.updateStateOf(_titleId,'additionPlacement',state.additionPlacement);tsfTitle.updateStateOf(_titleId,'hasLegacy',!!(state.hasLegacy||false));}
const updateTitleAdditions=event=>{let addAdditions=!event.target.checked;if(l10n.params.additionsForcedDisabled){addAdditions=false;}else if(l10n.params.additionsForcedEnabled){addAdditions=true;}
tsfTitle.updateStateOf(_titleId,'addAdditions',addAdditions);}
const blogNameTrigger=document.getElementById('autodescription_title_no_blogname');if(blogNameTrigger){blogNameTrigger.addEventListener('change',updateTitleAdditions);blogNameTrigger.dispatchEvent(new Event('change'));}
const setTitleVisibilityPrefix=visibility=>{let prefixValue='';switch(visibility){case 'password':prefixValue=tsfTitle.protectedPrefix;break;case 'private':prefixValue=tsfTitle.privatePrefix;break;default:case 'public':prefixValue='';break;}
tsfTitle.updateStateOf(_titleId,'prefixValue',prefixValue);}
$(document).on('tsf-updated-gutenberg-visibility',(event,visibility)=>setTitleVisibilityPrefix(visibility));const setClassicTitleVisibilityPrefix=event=>{let visibility=$('#visibility').find('input:radio:checked').val();if('password'===visibility){let pass=$('#visibility').find('#post_password').val();if(!pass||!pass.length){visibility='public';}}
setTitleVisibilityPrefix(visibility);}
document.querySelector('#visibility .save-post-visibility')?.addEventListener('click',setClassicTitleVisibilityPrefix);if(l10n.states.isPrivate){setTitleVisibilityPrefix('private');}else if(l10n.states.isProtected){setTitleVisibilityPrefix('password');}
const updateDefaultTitle=val=>{val=val?.trim()||'';let defaultTitle=tsfTitle.stripTitleTags?tsf.stripTags(val):val
tsfTitle.updateStateOf(_titleId,'defaultTitle',defaultTitle||tsfTitle.untitledTitle);}
if(!l10n.params.isFront){const classicTitleInput=document.querySelector('#titlewrap #title');classicTitleInput&&classicTitleInput.addEventListener('input',event=>updateDefaultTitle(event.target.value));$(document).on('tsf-updated-gutenberg-title',(event,title)=>updateDefaultTitle(title));}
tsfTitle.enqueueUnregisteredInputTrigger(_titleId);}
const _initDescriptionListeners=()=>{const descInput=document.getElementById(_descId);if(!descInput)return;tsfDescription.setInputElement(descInput);const state=JSON.parse(document.getElementById(`tsf-description-data_${_descId}`)?.dataset.state||0);if(state){tsfDescription.updateStateOf(_descId,'allowReferenceChange',!state.refDescriptionLocked);tsfDescription.updateStateOf(_descId,'defaultDescription',state.defaultDescription.trim());tsfDescription.updateStateOf(_descId,'hasLegacy',!!(state.hasLegacy||false));}
tsfDescription.enqueueUnregisteredInputTrigger(_descId);const setDescriptionVisibility=visibility=>{let oldUseDefaultDescription=tsfDescription.getStateOf(_descId,'useDefaultDescription'),useDefaultDescription=true;switch(visibility){case 'password':case 'private':useDefaultDescription=false;break;default:case 'public':useDefaultDescription=true;break;}
if(useDefaultDescription!==oldUseDefaultDescription)
tsfDescription.updateStateOf(_descId,'useDefaultDescription',useDefaultDescription);}
$(document).on('tsf-updated-gutenberg-visibility',(event,visibility)=>setDescriptionVisibility(visibility));const setClassicDescriptionVisibilityPrefix=event=>{let visibility=$('#visibility').find('input:radio:checked').val();if('password'===visibility){let pass=$('#visibility').find('#post_password').val();if(!pass||!pass.length){visibility='public';}}
setDescriptionVisibility(visibility);}
document.querySelector('#visibility .save-post-visibility')?.addEventListener('click',setClassicDescriptionVisibilityPrefix);if(l10n.states.isPrivate){setDescriptionVisibility('private');}else if(l10n.states.isProtected){setDescriptionVisibility('password');}}
const _initSocialListeners=()=>{tsfSocial.setInputInstance(_socialGroup,_titleId,_descId);const groupData=JSON.parse(document.getElementById(`tsf-social-data_${_socialGroup}`)?.dataset.settings||0);if(!groupData)return;tsfSocial.updateStateOf(_socialGroup,'addAdditions',groupData.og.state.addAdditions);tsfSocial.updateStateOf(_socialGroup,'defaults',{ogTitle:groupData.og.state.defaultTitle,twTitle:groupData.tw.state.defaultTitle,ogDesc:groupData.og.state.defaultDesc,twDesc:groupData.tw.state.defaultDesc,});tsfSocial.updateStateOf(_socialGroup,'inputLocks',{ogTitle:groupData.og.state?.titleLock||false,twTitle:groupData.tw.state?.titleLock||false,ogDesc:groupData.og.state?.descLock||false,twDesc:groupData.tw.state?.descLock||false,});}
const _initGeneralListeners=()=>{const enqueueGeneralInputListeners=()=>{tsfTitle.enqueueUnregisteredInputTrigger(_titleId);tsfDescription.enqueueUnregisteredInputTrigger(_descId);}
$('#tsf-flex-inpost-tab-general').on('tsf-flex-tab-toggled',enqueueGeneralInputListeners);window.addEventListener('tsf-flex-resize',enqueueGeneralInputListeners);}
const _initTooltipBoundaries=()=>{if(!l10n.states.isGutenbergPage)return;'tsfTT'in window&&tsfTT.addBoundary('#editor');document.addEventListener('tsf-gutenberg-sidebar-opened',()=>{'tsfTT'in window&&tsfTT.addBoundary('.edit-post-sidebar .components-panel');});}
const _initUpdateMetaBox=()=>{if(!l10n.states.isGutenbergPage)return;const seobar=document.querySelector('.tsf-seo-bar');const seobarAjaxLoader=document.querySelector('#tsf-doing-it-right-wrap .tsf-ajax');const imageUrl=document.getElementById('autodescription_socialimage-url');const _ogDescription=tsfSocial.getInputInstance(_socialGroup)?.inputs?.ogDesc;const _twDescription=tsfSocial.getInputInstance(_socialGroup)?.inputs?.twDesc;const getData={seobar:!!seobar,metadescription:!!document.getElementById(_descId),ogdescription:!!_ogDescription,twdescription:!!_twDescription,imageurl:!!imageUrl,}
const onSuccess=response=>{response=tsf.convertJSONResponse(response);const fadeTime=75;setTimeout(()=>{if('tsfDescription'in window){tsfDescription.updateStateOf(_descId,'defaultDescription',response.data.metadescription.trim());}
if('tsfSocial'in window){const socialDefaults=tsfSocial.getStateOf(_socialGroup,'defaults');socialDefaults.ogDesc=response.data.ogdescription.trim();socialDefaults.twDesc=response.data.twdescription.trim();tsfSocial.updateStateOf(_socialGroup,'defaults',socialDefaults);}
if(imageUrl){imageUrl.placeholder=tsf.decodeEntities(response.data.imageurl);imageUrl.dispatchEvent(new Event('change'));}
'tsfAys'in window&&tsfAys.reset();},fadeTime);$(seobar).fadeOut(fadeTime,()=>{seobarAjaxLoader&&tsf.unsetAjaxLoader(seobarAjaxLoader,true);seobar.innerHTML=response.data.seobar}).fadeIn(250,()=>{'tsfTT'in window&&tsfTT.triggerReset();});};const onFailure=()=>{seobarAjaxLoader&&tsf.unsetAjaxLoader(seobarAjaxLoader,false);}
document.addEventListener('tsf-gutenberg-onsave',()=>{seobarAjaxLoader&&tsf.resetAjaxLoader(seobarAjaxLoader);seobarAjaxLoader&&tsf.setAjaxLoader(seobarAjaxLoader);wp.ajax.send('tsf_update_post_data',{data:{nonce:tsf.l10n.nonces.edit_posts,post_id:l10n.states.id,get:getData,},timeout:7000,}).done(onSuccess).fail(onFailure);});}
const _loadSettings=()=>{_initVisibilityListeners();_initTitleListeners();_initDescriptionListeners();_initSocialListeners();_initGeneralListeners();}
const _readySettings=()=>{_doFlexResizeListener();_initTabs();_initTooltipBoundaries();_initUpdateMetaBox();}
return Object.assign({load:()=>{document.body.addEventListener('tsf-onload',_loadSettings);document.body.addEventListener('tsf-ready',_readySettings);}},{l10n});}(jQuery);window.tsfPost.load();