'use strict';window.tsfPTGB=function(){const l10n='undefined'!==typeof tsfPTL10n&&tsfPTL10n;const supportedTaxonomies=l10n.taxonomies;const{createElement,Fragment,Component,useState,useEffect}=wp.element;const{SelectControl}=wp.components;const{useSelect}=wp.data;const{unescape}=lodash;const EMPTY_ARRAY=[];const DEFAULT_QUERY={per_page:-1,orderby:'id',order:'asc',_fields:'id,name',};const _geti18n=(taxonomySlug,what)=>supportedTaxonomies[taxonomySlug]?.i18n[what]||'';let _registeredFields={};const _primaryTerm=taxonomySlug=>{const _dataHolder=()=>document.getElementById(`autodescription[_primary_term_${taxonomySlug}]`);const get=()=>+_dataHolder().value;const set=id=>+(_dataHolder().value=+id);const revalidate=selectedTerms=>{const primaryTerm=get();if(selectedTerms.includes(primaryTerm))
return primaryTerm;return set(selectedTerms?.[0]||0);}
const register=()=>{const wrap=document.getElementById('tsf-gutenberg-data-holder');if(!wrap)return _registeredFields[taxonomySlug]=false;wrap.insertAdjacentHTML('beforeend',wp.template('tsf-primary-term-selector')({taxonomy:supportedTaxonomies[taxonomySlug]}));return _registeredFields[taxonomySlug]=true;}
const isRegistered=()=>_registeredFields[taxonomySlug]||false;return{get,set,revalidate,register,isRegistered};}
const _initPrimaryTerm=()=>{if(!Object.keys(supportedTaxonomies).length)return;function primaryTermSelector({taxonomySlug,_legacySelectedTerms}){const primaryTerm=_primaryTerm(taxonomySlug);const[selection,setSelection]=useState(primaryTerm.get());const[_legacyAvailableTerms,_setLegacyAvailableTerms]=useState(false);const[_legacyIsResolving,_setLegacyIsResolving]=useState(false);const{selectedTerms,loading,availableTerms,_taxonomy,}=useSelect(select=>{const{getTaxonomy,getEntityRecords,isResolving}=select('core');const{getEditedPostAttribute}=select('core/editor');const _taxonomy=getTaxonomy(taxonomySlug);const _query=['taxonomy',taxonomySlug,DEFAULT_QUERY];return{selectedTerms:getEditedPostAttribute(_taxonomy?.rest_base)||EMPTY_ARRAY,loading:_legacyIsResolving||isResolving('getEntityRecords',_query),availableTerms:_legacyAvailableTerms||getEntityRecords(..._query)||EMPTY_ARRAY,_taxonomy,};},[taxonomySlug,_legacyIsResolving,_legacyAvailableTerms]);useEffect(()=>{if(!selectedTerms.includes(+selection)||primaryTerm.get()!==+selection){primaryTerm.revalidate(selectedTerms);setSelection(primaryTerm.get());}},[selectedTerms]);useEffect(()=>{if(_taxonomy?.rest_base&&_legacySelectedTerms?.length&&!_legacyIsResolving){if(!_legacyAvailableTerms?.length||_legacySelectedTerms.filter(id=>!availableTerms.map(term=>term.id).includes(id)).length){_setLegacyIsResolving(true);wp.apiFetch({path:wp.url?.addQueryArgs(`/wp/v2/${ _taxonomy.rest_base }`,DEFAULT_QUERY),}).then(terms=>{_setLegacyAvailableTerms(terms);},).finally(()=>{_setLegacyIsResolving(false);});}}
return()=>{_setLegacyIsResolving(false);};},[_legacySelectedTerms]);if(selectedTerms?.length<2){primaryTerm.set(0);return null;}
const onChange=termId=>{if(!selectedTerms.includes(+termId))return;primaryTerm.set(termId);setSelection(primaryTerm.get());'tsfAys'in window&&tsfAys.registerChange();};const getSelectOptions=()=>{return availableTerms.map(term=>selectedTerms.includes(term?.id)&&{value:term.id,label:unescape(term?.name)}).filter(Boolean)||'';};const isDisabled=()=>!(selectedTerms.length&&availableTerms.length&&!loading);return createElement(SelectControl,{label:_geti18n(taxonomySlug,'selectPrimary'),value:selection,className:'tsf-pt-gb-selector',onChange:onChange,options:getSelectOptions(),disabled:isDisabled(),},);}
const PrimaryTermSelectorFilter=OriginalComponent=>class extends Component{render(){if(!_primaryTerm(this.props?.slug).isRegistered())
return createElement(OriginalComponent,{...this.props});return createElement(Fragment,null,createElement(OriginalComponent,{...this.props},),createElement(primaryTermSelector,{taxonomySlug:this.props?.slug,_legacySelectedTerms:this.props?.terms,},));}}
for(let taxonomySlug in supportedTaxonomies)
_primaryTerm(taxonomySlug).register();wp.hooks.addFilter('editor.PostTaxonomyType','tsf/pt',PrimaryTermSelectorFilter);}
return Object.assign({load:()=>{document.body.addEventListener('tsf-onload',_initPrimaryTerm);}},{l10n});}();window.tsfPTGB.load();