'use strict';window.tsfTerm=function(){const l10n='undefined'!==typeof tsfTermL10n&&tsfTermL10n;const _titleId='autodescription-meta[doctitle]';const _descId='autodescription-meta[description]';const _socialGroup='autodescription_social_tt';const _initVisibilityListeners=()=>{const indexSelect=document.getElementById('autodescription-meta[noindex]');let canonicalUrl='',showcanonicalPh=true;const updateCanonicalPlaceholder=()=>{let canonicalInput=document.getElementById('autodescription-meta[canonical]');if(!canonicalInput)return;canonicalUrl||=canonicalInput.placeholder;canonicalInput.placeholder=showcanonicalPh?canonicalUrl:'';}
const setRobotsIndexingState=value=>{let type='';switch(+value){case 0:type=indexSelect.dataset.defaultUnprotected;break;case-1:type='index';break;case 1:type='noindex';break;}
if('noindex'===type){showcanonicalPh=false;}else{showcanonicalPh=true;}
updateCanonicalPlaceholder();}
if(indexSelect){indexSelect.addEventListener('change',event=>setRobotsIndexingState(event.target.value));setRobotsIndexingState(indexSelect.value);}}
const _initTitleListeners=()=>{tsfTitle.setInputElement(document.getElementById(_titleId));const state=JSON.parse(document.getElementById(`tsf-title-data_${_titleId}`)?.dataset.state||0);if(state){tsfTitle.updateStateOf(_titleId,'allowReferenceChange',!state.refTitleLocked);tsfTitle.updateStateOf(_titleId,'defaultTitle',state.defaultTitle.trim());tsfTitle.updateStateOf(_titleId,'addAdditions',state.addAdditions);tsfTitle.updateStateOf(_titleId,'useSocialTagline',!!(state.useSocialTagline||false));tsfTitle.updateStateOf(_titleId,'additionValue',state.additionValue.trim());tsfTitle.updateStateOf(_titleId,'additionPlacement',state.additionPlacement);tsfTitle.updateStateOf(_titleId,'hasLegacy',!!(state.hasLegacy||false));}
const termPrefix=tsf.escapeString(l10n.params.termPrefix);const updateTitleAdditions=event=>{let addAdditions=!event.target.checked;if(l10n.params.additionsForcedDisabled)
addAdditions=false;tsfTitle.updateStateOf(_titleId,'addAdditions',addAdditions);}
const blogNameTrigger=document.getElementById('autodescription-meta[title_no_blog_name]');if(blogNameTrigger){blogNameTrigger.addEventListener('change',updateTitleAdditions);blogNameTrigger.dispatchEvent(new Event('change'));}
const updateDefaultTitle=val=>{val=val?.trim();let title=tsfTitle.stripTitleTags?tsf.stripTags(val):val;title||=tsfTitle.untitledTitle;let defaultTitle;if(window.isRtl){defaultTitle=`${title} ${termPrefix}`;}else{defaultTitle=`${termPrefix} ${title}`;}
tsfTitle.updateStateOf(_titleId,'defaultTitle',defaultTitle);}
document.querySelector('#edittag #name')?.addEventListener('input',event=>updateDefaultTitle(event.target.value));tsfTitle.enqueueUnregisteredInputTrigger(_titleId);}
const _initDescriptionListeners=()=>{tsfDescription.setInputElement(document.getElementById(_descId));const state=JSON.parse(document.getElementById(`tsf-description-data_${_descId}`)?.dataset.state||0);if(state){tsfDescription.updateStateOf(_descId,'defaultDescription',state.defaultDescription.trim());tsfDescription.updateStateOf(_descId,'hasLegacy',!!(state.hasLegacy||false));}
tsfDescription.enqueueUnregisteredInputTrigger(_descId);}
const _initSocialListeners=()=>{tsfSocial.setInputInstance(_socialGroup,_titleId,_descId);const groupData=JSON.parse(document.getElementById(`tsf-social-data_${_socialGroup}`)?.dataset.settings||0);if(!groupData)return;tsfSocial.updateStateOf(_socialGroup,'addAdditions',groupData.og.state.addAdditions);tsfSocial.updateStateOf(_socialGroup,'defaults',{ogTitle:groupData.og.state.defaultTitle,twTitle:groupData.tw.state.defaultTitle,ogDesc:groupData.og.state.defaultDesc,twDesc:groupData.tw.state.defaultDesc,});}
const _loadSettings=()=>{_initVisibilityListeners();_initTitleListeners();_initDescriptionListeners();_initSocialListeners();}
const _readySettings=()=>{}
return Object.assign({load:()=>{document.body.addEventListener('tsf-onload',_loadSettings);document.body.addEventListener('tsf-ready',_readySettings);}},{l10n});}();window.tsfTerm.load();