'use strict';window.tsfTitle=function(){const l10n='undefined'!==typeof tsfTitleL10n&&tsfTitleL10n;const untitledTitle=tsf.escapeString(l10n.params.untitledTitle);const protectedPrefix=tsf.escapeString(l10n.i18n.protectedTitle);const privatePrefix=tsf.escapeString(l10n.i18n.privateTitle);const stripTitleTags=!!l10n.params.stripTitleTags;const titleInputInstances=new Map();const states={};const additionsStack=new Map();const prefixStack=new Map();const _getAdditionsValue=id=>additionsStack.get(id)||'';const _getPrefixValue=id=>prefixStack.get(id)||'';const _setAdditionsValue=(id,value)=>additionsStack.set(id,value)&&_getAdditionsValue(id);const _setPrefixValue=(id,value)=>prefixStack.set(id,value)&&_getPrefixValue(id);const _getHoverPrefixElement=id=>document.getElementById(`tsf-title-placeholder-prefix_${id}`)||document.createElement('span');const _getHoverAdditionsElement=id=>document.getElementById(`tsf-title-placeholder-additions_${id}`)||document.createElement('span');const setInputElement=element=>{titleInputInstances.set(element.id,element);states[element.id]={showPrefix:true,allowReferenceChange:true,defaultTitle:'',separator:l10n.states.titleSeparator,prefixPlacement:l10n.states.prefixPlacement,}
_loadTitleActions(element);return getInputElement(element.id);}
const getInputElement=id=>titleInputInstances.get(id);const getStateOf=(id,part)=>part?states[id]?.[part]:states[id];const updateStateOf=(id,part,value)=>{if(states[id][part]===value)return;states[id][part]=value;switch(part){case 'showPrefix':case 'prefixValue':case 'prefixPlacement':_updatePrefixValue(id);enqueueTriggerInput(id);break;case 'addAdditions':case 'separator':case 'additionValue':case 'additionPlacement':_updateAdditionsValue(id);enqueueTriggerInput(id);break;case 'allowReferenceChange':case 'defaultTitle':default:enqueueTriggerInput(id);break;}}
const updateStateAll=(part,value,except)=>{except=Array.isArray(except)?except:[except];titleInputInstances.forEach(element=>{if(except.includes(element.id))return;updateStateOf(element.id,part,value);});}
const _getTitleReferences=id=>{let references=[document.getElementById(`tsf-title-reference_${id}`)];if(getStateOf(id,'hasLegacy')){let legacy=document.getElementById('tsf-title-reference');legacy&&references.unshift(legacy);}
return references;}
const _getTitleNaReferences=id=>[document.getElementById(`tsf-title-noadditions-reference_${id}`)];const _setReferenceTitle=event=>{const references=_getTitleReferences(event.target.id),referencesNa=_getTitleNaReferences(event.target.id);if(!references[0]||!referencesNa[0])return;const allowReferenceChange=getStateOf(event.target.id,'allowReferenceChange');let text=allowReferenceChange&&event.target.value.trim()||getStateOf(event.target.id,'defaultTitle')||'',textNa=text;if(text.length&&allowReferenceChange){let prefix=_getPrefixValue(event.target.id),additions=_getAdditionsValue(event.target.id);if(prefix.length&&getStateOf(event.target.id,'showPrefix')){switch(getStateOf(event.target.id,'prefixPlacement')){case 'before':if(window.isRtl){text=text+prefix;}else{text=prefix+text;}
break;case 'after':if(window.isRtl){text=prefix+text;}else{text=text+prefix;}
break;}
textNa=text;}
if(additions.length){switch(getStateOf(event.target.id,'additionPlacement')){case 'before':text=additions+text;break;case 'after':text=text+additions;break;}}}
const referenceValue=tsf.escapeString(tsf.decodeEntities(tsf.sDoubleSpace(tsf.sTabs(tsf.sSingleLine(text).trim()))));const referenceNaValue=tsf.escapeString(tsf.decodeEntities(tsf.sDoubleSpace(tsf.sTabs(tsf.sSingleLine(textNa).trim()))));const changeEvent=new Event('change');references.forEach(reference=>{reference.innerHTML=referenceValue;setTimeout(()=>{reference.dispatchEvent(changeEvent)},0);});referencesNa.forEach(referenceNa=>{referenceNa.innerHTML=referenceNaValue;setTimeout(()=>{referenceNa.dispatchEvent(changeEvent)},0);});}
const _updateAdditionsValue=id=>{let value='',additionsValue='',separator='';if(getStateOf(id,'addAdditions')){additionsValue=tsf.escapeString(tsf.decodeEntities(getStateOf(id,'additionValue')));separator=getStateOf(id,'separator');}
if(additionsValue){switch(getStateOf(id,'additionPlacement')){case 'before':value=`${additionsValue} ${separator} `;break;case 'after':value=` ${separator} ${additionsValue}`;break;}}
_getHoverAdditionsElement(id).innerHTML=_setAdditionsValue(id,value||'');}
const _updatePrefixValue=id=>{let value='',showPrefix=getStateOf(id,'showPrefix'),prefixValue=getStateOf(id,'prefixValue');if(showPrefix&&prefixValue){switch(getStateOf(id,'prefixPlacement')){case 'before':if(window.isRtl){value=` ${prefixValue}`;}else{value=`${prefixValue} `;}
break;case 'after':if(window.isRtl){value=`${prefixValue} `;}else{value=` ${prefixValue}`;}
break;}}
_getHoverPrefixElement(id).innerHTML=_setPrefixValue(id,value||'');}
const _updateHoverPlacement=event=>{let hoverAdditionsElement=_getHoverAdditionsElement(event.target.id),hoverPrefixElement=_getHoverPrefixElement(event.target.id);if(!hoverAdditionsElement&&!hoverPrefixElement)
return;const input=event.target,inputValue=event.target.value;const hasPrefixValue=_getPrefixValue(event.target.id).length&&getStateOf(event.target.id,'showPrefix'),hasAdditionsValue=!!_getAdditionsValue(event.target.id).length;if(!hasPrefixValue&&hoverPrefixElement)
hoverPrefixElement.style.display='none';if(!hasAdditionsValue&&hoverAdditionsElement)
hoverAdditionsElement.style.display='none';if(!hasPrefixValue&&!hasAdditionsValue){input.style.textIndent='initial';return;}
if(!inputValue.length){input.style.textIndent='initial';if(hoverPrefixElement)hoverPrefixElement.style.display='none';if(hoverAdditionsElement)hoverAdditionsElement.style.display='none';return;}
const inputStyles=getComputedStyle(input),inputRect=input.getBoundingClientRect();const paddingTop=parseInt(inputStyles.paddingTop),paddingRight=parseInt(inputStyles.paddingRight),paddingBottom=parseInt(inputStyles.paddingBottom),paddingLeft=parseInt(inputStyles.paddingLeft),borderTop=parseInt(inputStyles.borderTopWidth),borderRight=parseInt(inputStyles.borderRightWidth),borderBottom=parseInt(inputStyles.borderBottomWidth),borderLeft=parseInt(inputStyles.borderTopWidth),marginTop=parseInt(inputStyles.marginTop),marginRight=parseInt(inputStyles.marginRight),marginBottom=parseInt(inputStyles.marginBottom),marginLeft=parseInt(inputStyles.marginLeft);const offsetPosition=window.isRtl?'right':'left',leftOffset=paddingLeft+borderLeft+marginLeft,rightOffset=paddingRight+borderRight+marginRight;let fontStyleCSS={display:inputStyles.display,lineHeight:inputStyles.lineHeight,fontFamily:inputStyles.fontFamily,fontWeight:inputStyles.fontWeight,fontSize:inputStyles.fontSize,letterSpacing:inputStyles.letterSpacing,marginTop:`${marginTop}px`,marginBottom:`${marginBottom}px`,paddingTop:`${paddingTop}px`,paddingBottom:`${paddingBottom}px`,border:`0 solid transparent`,borderTopWidth:`${borderTop}px`,borderBottomWidth:`${borderBottom}px`,};let additionsMaxWidth=0,additionsOffset=0,prefixOffset=0,totalIndent=0,prefixMaxWidth=0;if(hasPrefixValue){Object.assign(hoverPrefixElement.style,fontStyleCSS,{maxWidth:'initial'},);prefixMaxWidth=hoverPrefixElement.getBoundingClientRect().width;prefixOffset+=leftOffset;}
if(hasAdditionsValue){Object.assign(hoverAdditionsElement.style,fontStyleCSS,{maxWidth:'initial'},);const offsetElement=document.getElementById(`tsf-title-offset_${event.target.id}`);offsetElement.textContent=inputValue;Object.assign(offsetElement.style,{fontFamily:fontStyleCSS.fontFamily,fontWeight:fontStyleCSS.fontWeight,fontSize:fontStyleCSS.fontSize,letterSpacing:fontStyleCSS.letterSpacing,},);const textWidth=offsetElement.getBoundingClientRect().width;const additionsWidth=hoverAdditionsElement.getBoundingClientRect().width;switch(getStateOf(event.target.id,'additionPlacement')){case 'before':additionsMaxWidth=inputRect.width-rightOffset-paddingLeft-borderLeft-textWidth-prefixMaxWidth;if(additionsMaxWidth<0){prefixMaxWidth+=additionsMaxWidth;additionsMaxWidth=0;}
additionsMaxWidth=additionsMaxWidth<additionsWidth?additionsMaxWidth:additionsWidth;if(additionsMaxWidth<0)
additionsMaxWidth=0;totalIndent+=additionsMaxWidth;prefixOffset+=additionsMaxWidth;additionsOffset+=leftOffset;break;case 'after':additionsMaxWidth=inputRect.width-leftOffset-paddingRight-borderRight-textWidth-prefixMaxWidth;if(additionsMaxWidth<0){prefixMaxWidth+=additionsMaxWidth;additionsMaxWidth=0;}
additionsMaxWidth=additionsMaxWidth<additionsWidth?additionsMaxWidth:additionsWidth;if(additionsMaxWidth<0)
additionsMaxWidth=0;additionsOffset+=leftOffset+textWidth+prefixMaxWidth;break;}}
prefixMaxWidth=prefixMaxWidth<0?0:prefixMaxWidth;if(hasPrefixValue){Object.assign(hoverPrefixElement.style,{[offsetPosition]:`${prefixOffset}px`,maxWidth:`${prefixMaxWidth}px`,});totalIndent+=prefixMaxWidth;}
if(hasAdditionsValue){Object.assign(hoverAdditionsElement.style,{[offsetPosition]:`${additionsOffset}px`,maxWidth:`${additionsMaxWidth}px`,});}
input.style.textIndent=`${totalIndent}px`;}
const _updatePlaceholder=event=>{event.target.placeholder=_getTitleReferences(event.target.id)[0].textContent;}
const _updateCounter=event=>{if(!('tsfC'in window))return;let counter=document.getElementById(`${event.target.id}_chars`),reference=_getTitleReferences(event.target.id)[0];if(!counter)return;tsfC.updateCharacterCounter({e:counter,text:reference.innerHTML,field:'title',type:'search',});}
const _updatePixels=event=>{if(!('tsfC'in window))return;let pixels=document.getElementById(`${event.target.id}_pixels`),reference=_getTitleReferences(event.target.id)[0];if(!pixels)return;tsfC.updatePixelCounter({e:pixels,text:reference.innerHTML,field:'title',type:'search',});}
const triggerInput=id=>{if(id){let el=getInputElement(id);el&&el.dispatchEvent(new Event('input'));}else{titleInputInstances.forEach(element=>element.id&&triggerInput(element.id));}}
const triggerCounter=id=>{if(id){let el=getInputElement(id);el&&el.dispatchEvent(new CustomEvent('tsf-update-title-counter'));}else{titleInputInstances.forEach(element=>element.id&&triggerCounter(element.id));}}
const _onUpdateTitlesTrigger=event=>{_updateHoverPlacement(event);_setReferenceTitle(event);_updatePlaceholder(event);_onUpdateCounterTrigger(event);}
const _onUpdateCounterTrigger=event=>{_updateCounter(event);_updatePixels(event);}
let _enqueueTriggerInputBuffer={};const enqueueTriggerInput=id=>{(id in _enqueueTriggerInputBuffer)&&clearTimeout(_enqueueTriggerInputBuffer[id]);_enqueueTriggerInputBuffer[id]=setTimeout(()=>triggerInput(id),1000/60);}
const triggerUnregisteredInput=id=>{if('tsfAys'in window){let wereSettingsChanged=tsfAys.areSettingsChanged();triggerInput(id);if(!wereSettingsChanged&&tsfAys.areSettingsChanged())
tsfAys.reset();}else{triggerInput(id);}}
let _unregisteredTriggerBuffer={};const enqueueUnregisteredInputTrigger=id=>{(id in _unregisteredTriggerBuffer)&&clearTimeout(_unregisteredTriggerBuffer[id]);_unregisteredTriggerBuffer[id]=setTimeout(()=>triggerUnregisteredInput(id),1000/60);}
const _focusTitleInput=event=>{let input=document.getElementById(event.target.dataset.for);if(!input)return;let type=event.target.classList.contains('tsf-title-placeholder-additions')?'additions':'prefix',inputValue=input.value;input.focus();switch(event.detail){case 3:input.setSelectionRange(0,inputValue.length);break;case 2:let start,end;if('additions'===type&&'after'===getStateOf(input.id,'additionPlacement')||'prefix'===type&&window.isRtl){start=inputValue.replace(/(\w+|\s+)$/u,'').length;end=inputValue.length;}else{start=0;end=inputValue.length-inputValue.replace(/^(\s+|\w+)/u,'').length;}
input.setSelectionRange(start,end);break;case 1:default:let length='additions'===type&&'after'===getStateOf(input.id,'additionPlacement')?inputValue.length:0;input.setSelectionRange(length,length);break;}}
const _preventFocus=event=>event.preventDefault();let prevWidth=window.innerWidth;const _doResize=()=>{let width=window.innerWidth;if(prevWidth<width){if(prevWidth<=782&&width>=782){triggerUnregisteredInput();}}else{if(prevWidth>=782&&width<=782){triggerUnregisteredInput();}}
prevWidth=width;}
const _initAllTitleActions=()=>{window.addEventListener('tsf-resize',_doResize);window.addEventListener('tsf-counter-updated',()=>enqueueUnregisteredInputTrigger());}
const _loadTitleActions=titleInput=>{if(!titleInput instanceof Element)return;titleInput.addEventListener('input',_onUpdateTitlesTrigger);titleInput.addEventListener('tsf-update-title-counter',_onUpdateCounterTrigger);let hoverPrefix=_getHoverPrefixElement(titleInput.id),hoverAdditions=_getHoverAdditionsElement(titleInput.id);hoverPrefix.addEventListener('click',_focusTitleInput);hoverAdditions.addEventListener('click',_focusTitleInput);hoverPrefix.addEventListener('mousedown',_preventFocus);hoverAdditions.addEventListener('mousedown',_preventFocus);_updateAdditionsValue(titleInput.id);_updatePrefixValue(titleInput.id);enqueueUnregisteredInputTrigger(titleInput.id);}
return Object.assign({load:()=>{document.body.addEventListener('tsf-onload',_initAllTitleActions);},},{setInputElement,getInputElement,getStateOf,updateStateOf,updateStateAll,triggerCounter,triggerInput,enqueueTriggerInput,triggerUnregisteredInput,enqueueUnregisteredInputTrigger,},{l10n,untitledTitle,privatePrefix,protectedPrefix,stripTitleTags,});}();window.tsfTitle.load();