'use strict';window.tsf=function($){const l10n='undefined'!==typeof tsfL10n&&tsfL10n;const stripTags=str=>str.length&&str.replace(/(<([^>]+)?>?)/ig,'')||'';let _canUseDOMParserTest=void 0;const _canUseDOMParser=()=>{if(void 0===_canUseDOMParserTest){try{_canUseDOMParserTest=!!(new DOMParser()).parseFromString('','text/html');}catch(e){}
_canUseDOMParserTest=!!_canUseDOMParserTest;}
return _canUseDOMParserTest;}
let _decodeEntitiesDOMParser=void 0;const decodeEntities=str=>{if(!str?.length)return '';let map={'<':'&#x3C;','>':'&#x3E;',"\\":'&#x5C;',};str=str.replace(/[<>\\]/g,m=>map[m]);if(_canUseDOMParser()){_decodeEntitiesDOMParser=_decodeEntitiesDOMParser||new DOMParser();str=_decodeEntitiesDOMParser.parseFromString(str,'text/html').documentElement.textContent;}else{_decodeEntitiesDOMParser=_decodeEntitiesDOMParser||document.createElement('span');_decodeEntitiesDOMParser.innerHTML=str;str=ampHTMLtoText(_decodeEntitiesDOMParser.textContent);}
return str;}
const escapeString=str=>{if(!str.length)return '';let map={'&':'&#x26;','<':'&#x3C;','>':'&#x3E;','"':'&#x22;',"'":'&#x27;',"\\":'&#x5C;',"/":'&#x2F;',};return str.replace(/[&<>"'\\\/]/g,m=>map[m]);}
const ampHTMLtoText=str=>str.replace(/&amp;|&#x0{0,3}26;|&#38;/gi,'&');const sDoubleSpace=str=>str.replace(/\s{2,}/g,' ');const sSingleLine=str=>str.replace(/[\x0A\x0B\x0C\x0D]/g,' ');const sTabs=str=>str.replace(/\x09/g,' ');const getStringLength=str=>{let e,length=0;if(str.length){e=document.createElement('span');e.innerHTML=escapeString(str).trim();length=e.childNodes?.[0].nodeValue.length||0;}
return+length;}
const selectByValue=(element,value)=>{if(!element instanceof HTMLSelectElement)return;let _newIndex=void 0;for(let i=0;i<element.options.length;++i){if(value==element.options[i].value){_newIndex=i;break;}}
if(void 0===_newIndex){for(let i=0;i<element.options.length;++i){if(value==element.options[i].innerHTML){_newIndex=i;break;}}}
if(void 0!==_newIndex){element.selectedIndex=_newIndex;}}
const convertJSONResponse=response=>{let testJSON=response&&response.json||void 0,isJSON=1===testJSON;if(!isJSON){let _response=response;try{response=JSON.parse(response);isJSON=true;}catch(e){isJSON=false;}
if(!isJSON){response=_response;}}
return response;}
const setAjaxLoader=target=>{$(target).toggleClass('tsf-loading');}
const unsetAjaxLoader=(target,success)=>{let newclass='tsf-success',fadeTime=2500;if(!success){newclass='tsf-error';fadeTime=5000;}
$(target).removeClass('tsf-loading').addClass(newclass).fadeOut(fadeTime);}
const resetAjaxLoader=target=>{$(target).stop(false,true).empty().prop('class','tsf-ajax').show();}
const deprecatedFunc=(name,version,replacement)=>{version=version?` since The SEO Framework ${version}`:'';replacement=replacement?` Use ${replacement} instead.`:'';console.warn(`[DEPRECATED]: ${name} is deprecated${version}.${replacement}`);}
const _initPostboxToggle=()=>{let $postboxes=$('.postbox[id^="autodescription-"], .postbox#tsf-inpost-box');$(document).on('postbox-toggled',(event,$postbox)=>{if(!$postbox||!$postboxes.is($postbox))return;$postbox=$($postbox);let $input=$postbox.find('input:invalid, select:invalid, textarea:invalid');if(!$input.length)return;setTimeout(()=>{if($postbox.is(':hidden')){let id=$postbox.attr('id');$(`#${id}-hide`).trigger('click.postboxes');}else{if($postbox.hasClass('closed')){$postbox.find('.hndle, .handlediv').first().trigger('click.postboxes');}else{let firstInput=$input.get(0);if($(firstInput).is(':visible')){firstInput.reportValidity();}}}});});}
const _initNotices=()=>{const dismissNotice=event=>{let $notice=$(event.target).parents('.tsf-notice').first(),key=event.target.dataset&&event.target.dataset.key||void 0,nonce=event.target.dataset&&event.target.dataset.nonce||void 0;$notice.fadeTo(100,0,()=>{$notice.slideUp(100,()=>{$notice.remove();});});if(key&&nonce){wp.ajax.post('tsf_dismiss_notice',{tsf_dismiss_key:key,tsf_dismiss_nonce:nonce,});}}
const reset=()=>{document.querySelectorAll('.tsf-dismiss').forEach(el=>el.addEventListener('click',dismissNotice));}
document.body.addEventListener('tsf-reset-notice-listeners',reset);reset();}
let _dispatchEvents=new Set(),_loadedDispatchEvent=false;const dispatchAtInteractive=(element,eventName)=>{_dispatchEvents.add([element,eventName]);if(!_loadedDispatchEvent){document.body.addEventListener('tsf-interactive',_loopDispatchAtInteractive);_loadedDispatchEvent=true;}}
const _loopDispatchAtInteractive=()=>{_dispatchEvents.forEach(([element,eventName])=>{element.dispatchEvent(new Event(eventName));});}
let _debounceNoticeReset;const triggerNoticeReset=()=>{clearTimeout(_debounceNoticeReset);_debounceNoticeReset=setTimeout(()=>document.body.dispatchEvent(new CustomEvent('tsf-reset-notice-listeners')),100);}
let _debounceResize,_debounceResizeTrigger,_throttleResize=false;const _throttleResizeDebounceDelay=100;const _triggerResize=()=>{clearTimeout(_debounceResize);_debounceResize=setTimeout(()=>{_throttleResize=false},_throttleResizeDebounceDelay);if(_throttleResize){clearTimeout(_debounceResizeTrigger);_debounceResizeTrigger=setTimeout(_triggerResize,_throttleResizeDebounceDelay);}else{_throttleResize=true;dispatchEvent(new CustomEvent('tsf-resize'));}}
let isInteractive=false;const _triggerInteractive=()=>{if(!isInteractive){isInteractive=true;document.body.dispatchEvent(new CustomEvent('tsf-interactive'));}}
const _triggerReady=()=>{document.body.dispatchEvent(new CustomEvent('tsf-ready'));}
const _triggerOnLoad=()=>{document.body.dispatchEvent(new CustomEvent('tsf-onload'));}
let _isReady=false;const _doReady=()=>{if(_isReady)return;document.removeEventListener("DOMContentLoaded",_doReady);document.removeEventListener("load",_doReady);_triggerOnLoad();_initPostboxToggle();_initNotices();_triggerReady();_isReady=true;document.addEventListener('load',_triggerInteractive);setTimeout(_triggerInteractive,100);}
return Object.assign({load:()=>{if(document.readyState==="complete"||(document.readyState!=="loading"&&!document.documentElement.doScroll)){setTimeout(_doReady());}else{document.addEventListener("DOMContentLoaded",_doReady);document.addEventListener("load",_doReady);}
window.addEventListener('resize',_triggerResize);}},{stripTags,decodeEntities,escapeString,ampHTMLtoText,sDoubleSpace,sSingleLine,sTabs,getStringLength,selectByValue,convertJSONResponse,setAjaxLoader,unsetAjaxLoader,resetAjaxLoader,deprecatedFunc,triggerNoticeReset,dispatchAtInteractive,},{l10n});}(jQuery);window.tsf.load();