/*!
* myStickymenu by m.r.d.a
* v2.0.4
*/(function($){"use strict";$(document).ready(function($){if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)&&option.device_mobile!=1){return false;}else if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)!=true&&option.device_desktop!=1){return false;}
if($(option.mystickyClass)[0]){}else{console.log("myStickymenu: Entered Sticky Class does not exist, change it in Dashboard / Settings / myStickymenu / Sticky Class. ");return;}
var mystickyClass=document.querySelector(option.mystickyClass);var disableWidth=parseInt(option.disableWidth);var disableLargeWidth=parseInt(option.disableLargeWidth);var mystickyTransition=option.mystickyTransition;var activationHeight=parseInt(option.activationHeight);var adminBar=option.adminBar;var mysticky_disable_down=option.mysticky_disable_down;var viewportWidth;function calcViewportWidth(e){var e=window,a='inner';if(!('innerWidth'in window)){a='client';e=document.documentElement||document.body;}
viewportWidth=e[a+'Width'];}
calcViewportWidth();var parentmysticky=mystickyClass.parentNode;var wrappermysticky=document.createElement('div');var position=0;for(var i=0;i<parentmysticky.childNodes.length;i++){if(parentmysticky.childNodes[i]==mystickyClass){position=i;break;}}
wrappermysticky.id='mysticky-wrap';wrappermysticky.appendChild(mystickyClass);parentmysticky.insertBefore(wrappermysticky,parentmysticky.childNodes[position]);var parentnav=mystickyClass.parentNode;var wrappernav=document.createElement('div');wrappernav.id='mysticky-nav';parentnav.replaceChild(wrappernav,mystickyClass);wrappernav.appendChild(mystickyClass);if(activationHeight=="0"){var autoActivate=true;}
var mydivHeight;function initialDivHeight(){mydivHeight=(mystickyClass.offsetHeight);if(parseInt($(mystickyClass).css("marginBottom"))>0){wrappermysticky.style.marginBottom=($(mystickyClass).css("marginBottom"));}
if(mydivHeight=="0"){$(mystickyClass).children().filter(':visible').each(function(){mydivHeight=$(this).outerHeight(true);});}
if(viewportWidth>=disableWidth){}}
initialDivHeight();var myfixedHeight;function fixedDivHeight(){mystickyClass.classList.add('myfixed')
myfixedHeight=$(".myfixed").outerHeight();if(myfixedHeight=="0"){$(".myfixed").children().filter(':visible').each(function(){myfixedHeight=$(this).outerHeight(true);});}
mystickyClass.classList.remove('myfixed');}
fixedDivHeight();var adminBarHeight=0;function calcAdminBarHeight(){if((adminBar=="true")&&(viewportWidth>600)){if($("#wpadminbar")[0]){adminBarHeight=$('#wpadminbar').height();}else{adminBarHeight=0;}}else{adminBarHeight=0;}
if(mystickyTransition=="slide"){wrappernav.style.top="-"+myfixedHeight+"px";}else{wrappernav.style.top=adminBarHeight+"px";}}
calcAdminBarHeight();var mydivWidth;function initialDivWidth(){var rect=$(mystickyClass)[0].getBoundingClientRect();mydivWidth=rect.width;}
initialDivWidth();var deactivationHeight=activationHeight;function calcActivationHeight(){if(autoActivate==true){if(mystickyTransition=="slide"){activationHeight=$(mystickyClass).offset().top+mydivHeight-adminBarHeight;deactivationHeight=$(mystickyClass).offset().top+mydivHeight-adminBarHeight;if(mysticky_disable_down=="on"){deactivationHeight=$(mystickyClass).offset().top-adminBarHeight;}}
if(mystickyTransition=="fade"){if(mysticky_disable_down=="false"){activationHeight=$(mystickyClass).offset().top-adminBarHeight;deactivationHeight=$(mystickyClass).offset().top-adminBarHeight;}
if(mysticky_disable_down=="on"){activationHeight=$(mystickyClass).offset().top-adminBarHeight+mydivHeight;deactivationHeight=$(mystickyClass).offset().top-adminBarHeight;}}}}
calcActivationHeight();function headerDeactivateOnHeight(){if(autoActivate==true){if(mydivHeight>myfixedHeight){if(mystickyTransition=="slide"){deactivationHeight=activationHeight;if(mysticky_disable_down=="on"){deactivationHeight=activationHeight-myfixedHeight;}}else{activationHeight=mydivHeight;deactivationHeight=mydivHeight;}}}}
headerDeactivateOnHeight();var hasScrollY='scrollY'in window;var lastScrollTop=0;function onScroll(e){var mystickymenu_top_pos=$('.mysticky-welcomebar-fixed').css('top');var welcombar_position=$('.mysticky-welcomebar-fixed').data('position');var welcombar_height=$('.mysticky-welcomebar-fixed').outerHeight();var mystickymenu_show=$('.mysticky-welcomebar-fixed').length;var welcomebar_appear=$('body').hasClass('mysticky-welcomebar-apper');if(mystickymenu_show&&parseInt(mystickymenu_top_pos)>=0&&welcombar_position=='top'&&welcomebar_appear){var mystickymenu_pos=welcombar_height;adminBarHeight=0;}else{var mystickymenu_pos='';}
if(viewportWidth>=disableWidth){if(disableLargeWidth==0||viewportWidth<=disableLargeWidth){var y=hasScrollY?window.scrollY:document.documentElement.scrollTop;if(document.documentElement.scrollTop==0){wrappernav.classList.remove('wrapfixed');}
if(0<=y){if(y>=lastScrollTop){y>=activationHeight?mystickyClass.classList.add('myfixed'):"";y>=activationHeight?wrappernav.classList.add('wrapfixed'):"";y>=activationHeight?wrappermysticky.style.height=mydivHeight+'px':"";y>=activationHeight?mystickyClass.style.width=mydivWidth+"px":"";if(mystickyTransition=="slide"){if(mysticky_disable_down=="false"){y>=activationHeight+myfixedHeight-adminBarHeight?wrappernav.style.top=(adminBarHeight+mystickymenu_pos)+"px":wrappernav.style.top="-"+myfixedHeight+"px";}
if(mydivHeight>myfixedHeight){if(mysticky_disable_down=="false"){y<activationHeight+myfixedHeight?wrappernav.style.top="-"+mydivHeight+"px":'';y>=activationHeight+myfixedHeight?wrappernav.style.top=(adminBarHeight+mystickymenu_pos)+"px":'';}}}
wrappernav.classList.add('down');wrappernav.classList.remove('up');if(mysticky_disable_down=="on"){wrappernav.style.top="-"+(mydivHeight+adminBarHeight)+"px";jQuery('#mysticky-nav '+option.mystickyClass+'.elementor-sticky').hide();}}else{var x=hasScrollY?window.scrollY:document.documentElement.scrollTop;x>deactivationHeight?"":wrappermysticky.style.height="";x>deactivationHeight?"":mystickyClass.style.width="";if(mystickyTransition=="slide"){x>deactivationHeight?'':mystickyClass.classList.remove('myfixed');x>deactivationHeight?'':wrappernav.classList.remove('wrapfixed');if(mysticky_disable_down=="false"){x<deactivationHeight+myfixedHeight+200-adminBarHeight?wrappernav.style.top="-"+myfixedHeight+"px":'';}}else{x>deactivationHeight?"":mystickyClass.classList.remove('myfixed');x>deactivationHeight?"":wrappernav.classList.remove('wrapfixed');}
wrappernav.classList.remove('down');wrappernav.classList.add('up');if(mysticky_disable_down=="on"){wrappernav.style.top=(adminBarHeight+mystickymenu_pos)+"px";jQuery('#mysticky-nav '+option.mystickyClass).css('width',mydivWidth+"px");jQuery('#mysticky-nav '+option.mystickyClass+'.elementor-sticky').show();}}
lastScrollTop=y;}else{wrappernav.classList.remove('up');}}}}
document.addEventListener('scroll',onScroll);var width=$(window).width()
function OnResizeDocument(){if($(window).width()!=width){wrappernav.classList.remove('up');wrappernav.classList.remove('down');if($(".wrapfixed")[0]){}else{initialDivHeight();mystickyClass.style.removeProperty("width");initialDivWidth();}
calcViewportWidth();calcAdminBarHeight();fixedDivHeight();calcActivationHeight();headerDeactivateOnHeight();}}
window.addEventListener('resize',OnResizeDocument);window.addEventListener('orientationchange',OnResizeDocument);});})(jQuery);